# Generated by Django 6.0 on 2026-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsearchhistory',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
